name: Processing Libraries
on: 
  push: 
    branches: [master]
jobs:
  test:
    runs-on: main
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Restore
      run: dotnet restore --locked-mode
    - name: Publish
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
