name: Processing Libraries
on: 
  push: 
    branches: [master]
jobs:
  test:
    runs-on: main
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Restore
      run: dotnet restore --locked-mode
    - name: Build
      run: dotnet build -c Release
    - name: Pack TBot
      run: dotnet pack
    - name: Publish
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
