name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: FEDORENKO
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Build
        run: dotnet build
